demo_connection_1:
  host: "localhost"
  port: 3306
  user: "demo_user"
  passwd: "example_connection"
  db: "demo_db"
  charset: "utf8mb4"
  autocommit: "True"
  notes: "A sample MySQL connection"
demo_connection_2:
  host: "localhost"
  port: 3306
  user: "demo_user"
  passwd: "example_connection"
  db: "demo_db"
  charset: "utf8mb4"
  autocommit: "False"
  notes: "Another connection. Autocommit is off"